sudo: false
language: node_js
node_js:
  - node
  #- "5"
  #- "0.12"
install:
  - npm i
  - npm run dist
script: true
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: presteege.fr
  local_dir: dist
  acl: public_read
  region: us-west-2
  endpoint: presteege.fr.s3-website-us-west-2.amazonaws.com
  on:
    repo: presteege/presteege-react
notifications:
  email:
    on_failure: always
